spring:
  application:
    name: meet-me-server
  messages:
    basename: messages
    encoding: UTF-8
    fallback-to-system-locale: false

management:
  endpoints:
    web:
      exposure:
        include: health,info
